### PR TITLE
setup DB and do some minor code refactoring [Delivers #163386658]

### PR DESCRIPTION
**Pull request by HabibSentongo**
This PR adds a config file, updates the travis.yml file and add a DB management file.
I have tested the configurations and they successfully connect properly.
@wasswa-derick @rhytah @muwongenicholus @richien @mastula77

### CODE REVIEW

**Comment by richien** [comment]
This looks ok to me. Are the configs working for both test and dev DBs?

**Review by NicholusMuwonge — COMMENTED** [review]
well the changes are fine, I have one qn though, In the travis.yml file is the 'create' the db that travis will create to run the tests?

**Comment by HabibSentongo** [comment]
@richien the different configs are not in use yet, It was just some sort of getting ready for what's next. I learned those concepts from the resources that Derrick sent and from Rhytah.
@rhytah and @muwongenicholus yes I have seen that mistake in the travis file so I am going to correct it in the next commit

**Comment by richien** [comment]
@HabibSentongo , cool. And thank you for reminding me about the resources. Let me read through.

**Pull request merged**
