### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by HabibSentongo**
This PR merges all my endpoint features and their tests to the develop branch
@rwothoromo @davicken @richien @v1b3m @mastula77 @kalsmic @llwasampijja

### CODE REVIEW

**Comment by richien** [comment]
This looks ok to me

**Comment by v1b3m** [comment]
I don't get this chunk of code at all:
```
#fn to return incident dict with proper structure and type not errored
    def incident_struct(self, type):
        if type == "red-flag":
            self.incident_type = "red-flag"
        else:
            self.incident_type = "intervention"

        return {
            "incident_id": self.incident_id,
            "incident_title": self.incident_title,
            "incident_type": self.incident_type,
            "incident_status": self.incident_status,
            "created_on": self.created_on,
            "created_by": self.created_by,
            "location": self.location,
            "images": self.images,
            "videos": self.videos,
            "comment": self.comment
        }
```

replace this:
```
def all_red_flags():
    if len(red_flags_list) > 0:
``` 
with:
```
def all_red_flags():
    if red_flags_list:
```
Why would you return two different status codes, the status in the response is supposed to reflect the actual status code:
```return jsonify({
        'status': 204,
        'error': 'No records yet!'
    }), 200
```
Consider changing the list containing the red-flags with a dictionary so that you don't have to iterate through the whole list when searching for a given item:
```
if record['incident_id'] == red_flag_id:
            return jsonify({
                'status': 302,
                'data': [record]
            }),302
```
if the red-flags were stored in a dictionary, you'd have something similar to this:
```
if incident_id in redflags
```
Error code 417???

```
def create_red_flag():
    if not request.json:
        return jsonify({
            'status': 417,
            'error': 'No request data, Provide incident details'
        }), 417
```
just use double quotes:

```
'We can\'t identify you, Provide your ID'
```
can change to
```
"We can't identify you, Provide your ID"
```
If you used a dictionary:
```
red_flags_list.append(
        new_red_flag.incident_struct('red-flag')
    )
```
would change to:
```
red_flag_list['flag_id'] = new_red_flag.incident_struct('red-flag')
```
Please check through the document for the bootcamp, this is definitely not the required data format
```
'message': 'Incident {} has been recorded'.format(new_red_flag.incident_id)
```
Returning two different status codes makes no sense at all:
```
return jsonify({
            'status': 412,
            'error': 'New info missing, Provide new location'
        }), 417
```

Please check out this document for how your responses should look like: https://docs.google.com/document/d/1IeIvj-AI5So72ko5EmRtegDC4rjE0q7YbUAPwvOgnoU/edit#heading=h.uxitxeneuqsd

```
return jsonify({
                'status': 202,
                'data': [{
                    'message': 'Location of record {} updated to {}'.format(red_flag_id, new_location['location'])
                }]
            }), 202
```
Why don't you just clear the red-flag list

```
def tearDown(self):
        red_flags_list[:] = []
```

to

```
def tearDown(self):
        red_flags_list.clear()
```

A few points:
-Please try to follow pep8(use autopep8 to simplify the task)
-Also use pylint
-Work on your code maintainability, your readme shows an f, not a very good sign

All in all, thanks for the endeavor, that shows good progress

**Comment by HabibSentongo** [comment]
> I don't get this chunk of code at all:
> 
> ```
> #fn to return incident dict with proper structure and type not errored
>     def incident_struct(self, type):
>         if type == "red-flag":
>             self.incident_type = "red-flag"
>         else:
>             self.incident_type = "intervention"
> 
>         return {
>             "incident_id": self.incident_id,
>             "incident_title": self.incident_title,
>             "incident_type": self.incident_type,
>             "incident_status": self.incident_status,
>             "created_on": self.created_on,
>             "created_by": self.created_by,
>             "location": self.location,
>             "images": self.images,
>             "videos": self.videos,
>             "comment": self.comment
>         }
> ```
> replace this:
> 
> ```
> def all_red_flags():
>     if len(red_flags_list) > 0:
> ```
> with:
> 
> ```
> def all_red_flags():
>     if red_flags_list:
> ```
> Why would you return two different status codes, the status in the response is supposed to reflect the actual status code:
> 
> ```
>         'status': 204,
>         'error': 'No records yet!'
>     }), 200
> ```
> Consider changing the list containing the red-flags with a dictionary so that you don't have to iterate through the whole list when searching for a given item:
> 
> ```
> if record['incident_id'] == red_flag_id:
>             return jsonify({
>                 'status': 302,
>                 'data': [record]
>             }),302
> ```
> if the red-flags were stored in a dictionary, you'd have something similar to this:
> 
> ```
> if incident_id in redflags
> ```
> Error code 417???
> 
> ```
> def create_red_flag():
>     if not request.json:
>         return jsonify({
>             'status': 417,
>             'error': 'No request data, Provide incident details'
>         }), 417
> ```
> just use double quotes:
> 
> ```
> 'We can\'t identify you, Provide your ID'
> ```
> can change to
> 
> ```
> "We can't identify you, Provide your ID"
> ```
> If you used a dictionary:
> 
> ```
> red_flags_list.append(
>         new_red_flag.incident_struct('red-flag')
>     )
> ```
> would change to:
> 
> ```
> red_flag_list['flag_id'] = new_red_flag.incident_struct('red-flag')
> ```
> Please check through the document for the bootcamp, this is definitely not the required data format
> 
> ```
> 'message': 'Incident {} has been recorded'.format(new_red_flag.incident_id)
> ```
> Returning two different status codes makes no sense at all:
> 
> ```
> return jsonify({
>             'status': 412,
>             'error': 'New info missing, Provide new location'
>         }), 417
> ```
> Please check out this document for how your responses should look like: https://docs.google.com/document/d/1IeIvj-AI5So72ko5EmRtegDC4rjE0q7YbUAPwvOgnoU/edit#heading=h.uxitxeneuqsd
> 
> ```
> return jsonify({
>                 'status': 202,
>                 'data': [{
>                     'message': 'Location of record {} updated to {}'.format(red_flag_id, new_location['location'])
>                 }]
>             }), 202
> ```
> Why don't you just clear the red-flag list
> 
> ```
> def tearDown(self):
>         red_flags_list[:] = []
> ```
> to
> 
> ```
> def tearDown(self):
>         red_flags_list.clear()
> ```
> A few points:
> -Please try to follow pep8(use autopep8 to simplify the task)
> -Also use pylint
> -Work on your code maintainability, your readme shows an f, not a very good sign
> 
> All in all, thanks for the endeavor, that shows good progress

Thanks a lot @v1b3m
-for the status codes, I am correcting that. I had done so so that postman may not hide the returned data
-your ideas are great, I am going to do the needful

**Comment by v1b3m** [comment]
> > I don't get this chunk of code at all:
> > ```
> > #fn to return incident dict with proper structure and type not errored
> >     def incident_struct(self, type):
> >         if type == "red-flag":
> >             self.incident_type = "red-flag"
> >         else:
> >             self.incident_type = "intervention"
> > 
> >         return {
> >             "incident_id": self.incident_id,
> >             "incident_title": self.incident_title,
> >             "incident_type": self.incident_type,
> >             "incident_status": self.incident_status,
> >             "created_on": self.created_on,
> >             "created_by": self.created_by,
> >             "location": self.location,
> >             "images": self.images,
> >             "videos": self.videos,
> >             "comment": self.comment
> >         }
> > ```
> > replace this:
> > ```
> > def all_red_flags():
> >     if len(red_flags_list) > 0:
> > ```
> > with:
> > ```
> > def all_red_flags():
> >     if red_flags_list:
> > ```
> > Why would you return two different status codes, the status in the response is supposed to reflect the actual status code:
> > ```
> >         'status': 204,
> >         'error': 'No records yet!'
> >     }), 200
> > ```
> > Consider changing the list containing the red-flags with a dictionary so that you don't have to iterate through the whole list when searching for a given item:
> > ```
> > if record['incident_id'] == red_flag_id:
> >             return jsonify({
> >                 'status': 302,
> >                 'data': [record]
> >             }),302
> > ```
> > if the red-flags were stored in a dictionary, you'd have something similar to this:
> > ```
> > if incident_id in redflags
> > ```
> > Error code 417???
> > ```
> > def create_red_flag():
> >     if not request.json:
> >         return jsonify({
> >             'status': 417,
> >             'error': 'No request data, Provide incident details'
> >         }), 417
> > ```
> > just use double quotes:
> > ```
> > 'We can\'t identify you, Provide your ID'
> > ```
> > can change to
> > ```
> > "We can't identify you, Provide your ID"
> > ```
> > If you used a dictionary:
> > ```
> > red_flags_list.append(
> >         new_red_flag.incident_struct('red-flag')
> >     )
> > ```
> > would change to:
> > ```
> > red_flag_list['flag_id'] = new_red_flag.incident_struct('red-flag')
> > ```
> > Please check through the document for the bootcamp, this is definitely not the required data format
> > ```
> > 'message': 'Incident {} has been recorded'.format(new_red_flag.incident_id)
> > ```
> > Returning two different status codes makes no sense at all:
> > ```
> > return jsonify({
> >             'status': 412,
> >             'error': 'New info missing, Provide new location'
> >         }), 417
> > ```
> > Please check out this document for how your responses should look like: https://docs.google.com/document/d/1IeIvj-AI5So72ko5EmRtegDC4rjE0q7YbUAPwvOgnoU/edit#heading=h.uxitxeneuqsd
> > ```
> > return jsonify({
> >                 'status': 202,
> >                 'data': [{
> >                     'message': 'Location of record {} updated to {}'.format(red_flag_id, new_location['location'])
> >                 }]
> >             }), 202
> > ```
> > Why don't you just clear the red-flag list
> > ```
> > def tearDown(self):
> >         red_flags_list[:] = []
> > ```
> > to
> > ```
> > def tearDown(self):
> >         red_flags_list.clear()
> > ```
> > A few points:
> > -Please try to follow pep8(use autopep8 to simplify the task)
> > -Also use pylint
> > -Work on your code maintainability, your readme shows an f, not a very good sign
> > All in all, thanks for the endeavor, that shows good progress
> 
> Thanks a lot @v1b3m
> -for te status codes, I am correcting that. I had done so so that postman may not hide the returned data
> -your ideas are great, i am going to do the needful

You're welcome chief

**Comment by llwasampijja** [comment]
This is nice work @HabibSentongo . You wrote good unit tests and good coverage. In addition to what @v1b3m has noted, your application may even be better if you look into the issues that i noticed and have noted below: 
- unless you have a reason, i think the status codes should be the same, for the response and server.
- You need to validate the request to ensure that a user enters all and only the required fields.
- you also need to validate the comment field, to ensure that the user enters only the accepted type of the data.
- Basing on the challenge document, I think the images and videos fields should be of list type and data strings type.
- You should also validate the location to be a string of latitude and longitude and not words.
- Try to validate all the user inputs to avoid any unplanned errors or even app crashes

**Pull request merged**
